name: "FRPC Tunnel Client"
version: "1.0.10"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zu deinem eigenen FRP-Server (frpc via YAML)"
startup: services
boot: auto
init: false
ingress: false

options:
  server_addr: "ha-cloud.example.com"
  server_port: 7000
  subdomain: "kunde1"

schema:
  server_addr: str
  server_port: int
  subdomain: str

environment:
  SERVER_ADDR: $server_addr
  SERVER_PORT: $server_port
  SUBDOMAIN: $subdomain
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
