name: "HA-Tools Tunnel"
version: "1.0.14"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zum HA-Tools Server"
startup: services
boot: auto
init: false
ingress: false

options:
  server_addr: "ha-cloud.example.com"
  server_port: 7000
  subdomain: "kunde1"

schema:
  server_addr: str
  server_port: int
  subdomain: str

environment:
  # links: Name der env‑Var im Container
  # rechts: referenziert deine options oben
  SERVER_ADDR: "${server_addr}"
  SERVER_PORT: "${server_port}"
  SUBDOMAIN: "${subdomain}"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
