name: "FRPC Tunnel Client"
version: "1.0.8"
slug: "frpc_tunnel"
description: "Ermöglicht eine sichere Verbindung zu einem FRP-Server für Remote-Zugriff auf Home Assistant."
startup: services
boot: auto
init: false
ingress: false
options:
  server_addr: "dein-server.de"
  server_port: 7000
  subdomain: "kunde1"
schema:
  server_addr: str
  server_port: int
  subdomain: str
environment:
  server_addr: $server_addr
  server_port: $server_port
  subdomain: $subdomain
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
