name: "HA-Tools Tunnel"
version: "1.0.37"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zum HA-Tools Server"
startup: services
boot: auto
init: false
ingress: false
host_network: true

options:
  instance_id: "kunde1"
  local_port: 8123

schema:
  instance_id: str
  local_port: int
  
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
