name: "HA-Tools Tunnel"
version: "1.0.34"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zum HA-Tools Server mit automatischer Port-Erkennung"
startup: services
boot: auto
init: false
ingress: false
host_network: true
homeassistant_api: true
hassio_api: true

options:
  instance_id: "kunde1"

schema:
  instance_id: str

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
