name: "HA-Tools Tunnel"
version: "1.0.27"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zum HA-Tools Server"
startup: services
boot: auto
init: false
ingress: false
host_network: true

options:
  server_addr: "ha-cloud.example.com"
  server_port: 7000
  subdomain: "kunde1"

schema:
  server_addr: str
  server_port: int
  subdomain: str

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
