name: "FRPC Tunnel Client"
version: "1.0.4"
slug: "frpc_tunnel"
description: "Ermöglicht eine sichere Verbindung zu einem FRP-Server für Remote-Zugriff auf Home Assistant."
startup: services
boot: auto
init: false
ingress: false
options:
  server_addr: "ha-cloud.example.com"
  server_port: 7000
  subdomain: "ha-meinname"
schema:
  server_addr: str
  server_port: int
  subdomain: str
arch:
  - amd64
  - arm64
  - arm
