name: "FRPC Tunnel Client"
version: "1.0.11"
slug: "frpc_tunnel"
description: "Reverse-Tunnel zu deinem eigenen FRP-Server (frpc via YAML)"
startup: services
boot: auto
init: false
ingress: false

options:
  SERVER_ADDR: "ha-cloud.example.com"
  SERVER_PORT: 7000
  SUBDOMAIN: "kunde1"

schema:
  SERVER_ADDR: str
  SERVER_PORT: int
  SUBDOMAIN: str

environment:
  SERVER_ADDR: $SERVER_ADDR
  SERVER_PORT: $SERVER_PORT
  SUBDOMAIN: $SUBDOMAIN

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
